djwailer/bridge/urls.py
# -*- coding: utf-8 -*-

"""URLs for all views."""

from django.urls import path
from django.views.generic import RedirectView
from djwailer.bridge import views


urlpatterns = [
    path('unicode/<int: oid>)/', views.unicode_test, name='unicode_test'),
    path(
        '<str:content_type>/success/',
        views.submission_success,
        name='submission_success',
    ),
    path('<str:content_type>/', views.submission_form, name='submission_form'),
    path('', RedirectView.as_view(url="/bridge/")),
]

djwailer/urls.py
# -*- coding: utf-8 -*-

"""URLs for all views."""

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from djauth.views import loggedout


admin.autodiscover()

handler404 = 'djtools.views.errors.four_oh_four_error'
handler500 = 'djtools.views.errors.server_error'


urlpatterns = [
    # auth
    path(
        'accounts/login/',
        auth_views.LoginView.as_view(),
        {'template_name': 'registration/login.html'},
        name='auth_login',
    ),
    path(
        'accounts/logout/',
        auth_views.LogoutView.as_view(),
        {'next_page': reverse_lazy('auth_loggedout')},
        name='auth_logout',
    ),
    path(
        'accounts/loggedout/',
        loggedout,
        {'template_name': 'registration/logged_out.html'},
        name='auth_loggedout',
    ),
    path(
        'accounts/',
        RedirectView.as_view(url=reverse_lazy('auth_login')),
    ),
    path(
        'denied/',
        TemplateView.as_view(template_name='denied.html'),
        name='access_denied',
    ),
    # django admin and loginas
    path('rocinante/', include('loginas.urls')),
    path('rocinante/', admin.site.urls),
    # admin honeypot
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # bridge
    path('bridge/', include('djwailer.bridge.urls')),
    path(
        'bridget/',
        TemplateView.as_view(template_name='bridge/maintenance_mode.html'),
    ),
    path('', RedirectView.as_view(url='https://www.carthage.edu/bridge/submit/')),
]

djwailer/bridge/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.conf import settings
from djtools.fields.time import KungfuTimeField
from djwailer.core.models import CATEGORIES
from djwailer.core.models import LivewhaleEvents
from djwailer.core.models import LivewhaleNews
from htmllaundry import sanitize


if settings.DEBUG:
    REQ = {'class': 'required'}
else:
    REQ = {'class': 'required', 'required': 'required'}

SEND_TO = (
    ('', '---------'),
    (False, '[TEST] Communications'),
    (True, '[LIVE] Campus Community'),
)


class EventSubmissionForm(forms.ModelForm):
    """Calendar event submission form."""

    title = forms.CharField(max_length=255)
    description = forms.CharField(widget=forms.Textarea)
    location = forms.CharField(max_length=255, required=False)
    start_date = forms.DateField()
    end_date = forms.DateField()
    start_time = KungfuTimeField(
        label="Event starts at",
        help_text="(Format HH:MM am/pm)",
        required=False,
    )
    end_time = KungfuTimeField(
        label="Event Ends at",
        help_text="(Format HH:MM am/pm)",
        required=False,
    )
    category = forms.CharField(
        widget=forms.Select(choices=CATEGORIES, attrs=REQ),
    )
    entity = forms.CharField(
        label="Sponsoring department, office, or student organization",
        max_length=255,
        required=True,
    )
    contact_information = forms.CharField(
        required=True,
        widget=forms.Textarea,
        help_text="""
            Who should people contact for more information?
            Please include name and phone or email.
        """,
    )

    class Meta:
        """Information about the data model."""

        model = LivewhaleEvents
        fields = (
            'title',
            'description',
            'location',
            'start_date',
            'end_date',
            'start_time',
            'end_time',
            'category',
            'entity',
            'contact_information',
        )

    def clean_end_date(self):
        """Error handling and data integrity for the end date field."""
        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')
        if (start_date and end_date) and start_date > end_date:
            raise forms.ValidationError("""
                You must pick an end date later than the start date.
            """)
        return end_date

    def clean_end_time(self):
        """Error handling and data integrity for the end time field."""
        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')
        if (start_time and end_time) and start_time > end_time:
            raise forms.ValidationError("""
                You must pick an end time later than the start time.
            """)
        return end_time

    def clean(self):
        """Error handling and data integrity for various dependent fields."""
        cd = self.cleaned_data
        description = cd.get('description')
        if description:
            if cd.get('entity'):
                entity = """
                    <h4>SPONSORING DEPARTMENT, OFFICE, OR ORGANIZATION:</h4>
                """
                entity += '<p>{0}</p>'.format(cd['entity'])
                description += entity
            if cd.get('contact_information'):
                contact = '<h4>FOR MORE INFORMATION, CONTACT:</h4>'
                contact += '<p>{0}</p>'.format(cd['contact_information'])
                description += contact
            cd['description'] = sanitize(description)
        return cd


class NewsSubmissionForm(forms.ModelForm):
    """News story submission form."""

    headline = forms.CharField(max_length=255)
    body = forms.CharField(label="Body of Article", widget=forms.Textarea)
    summary = forms.CharField(
        label="""
            Short Summary (One-or two-sentence summary of your
            news that will serve as an introduction to your
            article)""",
        widget=forms.Textarea,
    )
    category = forms.CharField(
        widget=forms.Select(choices=CATEGORIES, attrs=REQ),
    )
    entity = forms.CharField(
        label="Sponsoring department, office, or student organization",
        max_length=255,
        required=False,
    )
    contact_information = forms.CharField(
        required=False,
        widget=forms.Textarea,
        help_text="""
            Who should people contact for more information?
            Please include name and phone or email.
        """,
    )

    class Meta:
        """Information about the data model."""

        model = LivewhaleNews
        fields = (
            'headline',
            'body',
            'summary',
            'category',
            'entity',
            'contact_information',
        )

    def clean(self):
        """Error handling and data integrity for various dependent fields."""
        cd = self.cleaned_data
        body = cd.get('body')
        if body:
            if cd.get('entity'):
                entity = """
                    <h4>SPONSORING DEPARTMENT, OFFICE, OR ORGANIZATION:</h4>
                """
                entity += '<p>{0}</p>'.format(cd['entity'])
                body += entity
            if cd.get('contact_information'):
                contact = '<h4>FOR MORE INFORMATION, CONTACT:</h4>'
                contact += '<p>{0}</p>'.format(cd['contact_information'])
                body += contact
            cd['body'] = sanitize(body)
        return cd

    def clean_summary(self):
        """Sanitize the html in the summary field."""
        return sanitize(self.cleaned_data.get('summary'))

djwailer/bridge/views.py
# -*- coding: utf-8 -*-

import os

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from djtools.utils.convert import str_to_class
from djtools.utils.mail import send_mail
from djtools.utils.users import in_group
from djwailer.bridge.forms import EventSubmissionForm
from djwailer.bridge.forms import NewsSubmissionForm
from djwailer.core.models import LivewhaleEvents as Event
from djwailer.core.models import LivewhaleNews as News


@login_required
def submission_form(request, content_type, oid=None):
    """Generic submission for form for both News and Events."""
    ct = content_type.capitalize()
    form_name = '{0}SubmissionForm'.format(ct)
    instance = None
    # fetch an object or 404
    if oid and request.user.is_superuser:
        mod = str_to_class('djwailer.core.models', ct)
        instance = get_object_or_404(mod.objects.using('livewhale'), pk=oid)

    email_template = 'bridge/{0}/email.html'.format(content_type)
    # try/catch works as 404 detector
    # and GET initialization for forms
    try:
        os.stat(os.path.join(settings.ROOT_DIR, 'templates', email_template))
    except Exception:
        raise Http404
    form = str_to_class('djwailer.bridge.forms', form_name)(instance=instance)
    if request.POST:
        form = str_to_class('djwailer.bridge.forms', form_name)(request.POST)
        if form.is_valid():
            usr = request.user
            cd = form.cleaned_data
            instance = form.save(commit=False)
            cd['user'] = usr
            instance.save(using='livewhale', data=cd)
            subject = "[The Bridge] {0}: submitted by {1} {2}".format(
                ct,
                usr.first_name,
                usr.last_name,
            )
            # recipients
            student = in_group(usr, 'carthageStudentStatus')
            staff = in_group(usr, 'carthageStaffStatus')
            if settings.DEBUG:
                to_list = [settings.MANAGERS[0][1]]
            else:
                if student and not staff:
                    to_list = [
                        settings.BRIDGE_STUDENT, settings.BRIDGE_COMMS, usr.email,
                    ]
                else:
                    to_list = [settings.BRIDGE_COMMS, usr.email]

            instance.user = usr
            bcc = settings.MANAGERS
            send_mail(
                request,
                to_list,
                subject,
                usr.email,
                'bridge/{0}/email.html'.format(content_type),
                instance,
                bcc,
            )
            return HttpResponseRedirect(
                reverse(
                    'submission_success',
                    kwargs={'content_type': content_type},
                ),
            )

    return render(
        request,
        'bridge/{0}/form.html'.format(content_type),
        {'form': form},
    )


def submission_success(request, content_type):
    """Display the form success page."""
    # try/catch works as 404 detector
    # and GET initialization for forms
    template = 'bridge/{0}/done.html'.format(content_type)
    try:
        os.stat(os.path.join(settings.ROOT_DIR, 'templates', template))
    except Exception:
        raise Http404
    return render(request, template, {'content_type': content_type})


def unicode_test(request, oid):
    """Simple view to test funky characters from the database."""
    funky = News.objects.using('livewhale').get(pk=oid)
    return render(request, 'bridge/unicode.html', {'funky': funky})

djwailer/templates/bridge/event/done.html
{% extends "bridge/event/form.html" %}
{% load livewhale_api %}
{% block title %}Submit {{content_type|capfirst}} to the Carthage Bridge{% endblock %}
{% block content %}
    <h2>Thank you for your submission to The Bridge</h2>
    <p>
        <a href="{% url 'submission_form' content_type %}">Submit another</a>?
    </p>
    {% get_lw_content as recurring_warning blurbs 2481 %}
    {{recurring_warning.body}}
{% endblock %}
{% block extra_content %}{% endblock %}

djwailer/templates/bridge/event/email.html
<h1>Event Submission</h1>
<h3>{{data.title|safe}}</h3>
<p>
    By:
    <a href="mailto:{{data.user.email}}">
        {{data.user.first_name}} {{data.user.last_name}}
    </a>
</p>
<h4>Description</h4>
<div style="width:600px;font-size:1.5em;">{{data.description|safe}}</div>
<hr>
<p>
    Thank you for your submission.<br>
    <a href="{{data.get_absolute_url}}">View your submission on The Bridge</a>.
    Student submissions will be accessible once they are approved,
    usually the next business day.
</p>
<p style="width:600px;font-size:.9em;">
    NOTE: The Office of Communications may edit the content for
    spelling, grammar, and adherence to the Carthage style guide.
</p>

djwailer/templates/bridge/event/form.html
{% extends "base.html" %}
{% load livewhale_api %}
{% block title %}Submit an Event to the Carthage Bridge{% endblock %}
{% block extra_javascript %}
<script src="//app.carthage.edu/static/vendor/jquery/ui/datepicker/js/jquery-ui-1.10.4.custom.min.js"
    type="text/javascript" charset="utf-8"></script>
<script src="//app.carthage.edu/static/vendor/jquery/plugins/ptTimeSelect/src/jquery.ptTimeSelect.js"
    type="text/javascript"></script>
<script src="//app.carthage.edu/static/vendor/jquery/plugins/trumbowyg/trumbowyg.min.js"></script>
<script type="text/javascript" charset="utf-8">
$(function() {
    var $wysiwyg = {
      btns: [
        ['formatting'], ['strong', 'em', 'del'], ['link'],
        ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
        ['unorderedList', 'orderedList'], ['horizontalRule'], ['viewHTML'],
      ],
      tagsToRemove: ['script', 'link'],
      removeformatPasted: true, semantic: true, autogrow: true, resetCss: true
    };
    $('#id_description').trumbowyg($wysiwyg);
    $('#id_summary').trumbowyg($wysiwyg);
    $('#id_body').trumbowyg($wysiwyg);
    $("#id_start_date, #id_end_date").datepicker({
        firstDay:0,appendText:"(format yyyy-mm-dd)",
        changeFirstDay:false,dateFormat:"yy-mm-dd",
        showOn:"both",
        buttonImage:"//app.carthage.edu/themes/shared/img/ico/calendar.gif",
        buttonImageOnly:true
    });
    $('#id_start_time').ptTimeSelect();
    $('#id_end_time').ptTimeSelect();
    $("#id_start_date").change(function () {
        var date = $(this).val();
        $("#id_end_date").val(date);
    });
    $('form#profile').submit(function(){
        /* check textarea for just br tag */
        $("textarea").each(function(){
            if (this.value == "<br>") {
                this.value = "";
            }
        });
        // disable submit button after users clicks it
        $(this).children('input[type=submit]').attr('disabled', 'disabled');
    });
});
</script>
{% endblock %}
{% block extra_style %}
<link href="//app.carthage.edu/static/vendor/jquery/ui/datepicker/css/smoothness/jquery-ui-1.10.4.custom.min.css"
    rel="stylesheet" type="text/css" />
<link href="//app.carthage.edu/static/vendor/jquery/plugins/ptTimeSelect/src/jquery.ptTimeSelect.css"
    rel="stylesheet" type="text/css" />
<link href="//app.carthage.edu/static/vendor/jquery/plugins/trumbowyg/trumbowyg.min.css"
    rel="stylesheet" type="text/css" />
<style type="text/css">
#ptTimeSelectCntr {color: #303030;background: #ebebeb;font: .74em Arial, Verdana, sans-serif;text-align: center;line-height: 1.6em;margin: 2.5em 0;}
.tab_content_container {
    width: 705px;
}
iframe {width:500px !important;height:300px !important;background: #fff;border: solid 1px #ccc;}
</style>
{% endblock %}
{% block content_head %}
    <h1 id="page_title">
         Submit an Event
    </h1>
{% endblock %}
{% block content %}
    {% get_lw_content as info blurbs 2745 %}
    {{info.body}}
{% endblock %}
{% block extra_content %}
    <div class="forms-container">
        {% include "includes/generic_form.html" %}
    </div>
{% endblock %}